on: [push, pull_request]

name: unit-tests

jobs:
  unit-tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: "3.6.1", jaspRequiredFilesBranch: "Windows",        libPath: "/R/library"}
          - {os: macOS-latest,   r: "3.6.1", jaspRequiredFilesBranch: "MacOS-Original", libPath: "/Frameworks/R.framework/Versions/3.6/Resources/library/"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz

      - name: Clone jasp-required-files
        run: git clone --branch=${{ matrix.config.jaspRequiredFilesBranch }} https://github.com/jasp-stats/jasp-required-files.git pkgs
        working-directory: ..

      - name: Set R library path
        run: |
          echo ".libPaths(c(file.path('..', 'pkgs', '${{ matrix.config.libPath }}'), .libPaths()))" >> ~/.Rprofile
          cat ~/.Rprofile
        shell: bash
      
      - name: testLib
        run: |
          print(.libPaths())
          print(paste("workspace:", Sys.getenv('GITHUB_WORKSPACE')))
          print(paste("home:", Sys.getenv('HOME')))
          print("files in ..:")
          list.files("..")
          .libPaths("../pkgs/R/library")
          print(.libPaths())
        shell: Rscript {0}

      - name: Install JAGS on macOS
        if: runner.os == 'macOS'
        run: |
          rm '/usr/local/bin/gfortran'
          brew install jags

      - name: Locate JAGS on Windows
        if: runner.os == 'Windows'
        run: |
          echo "Sys.setenv(JAGS_HOME = normalizePath(file.path(Sys.getenv('GITHUB_WORKSPACE'), '..', 'pkgs', '64', 'JAGS')))"  >> ~/.Rprofile
          cat ~/.Rprofile
        shell: bash

      - name: Setup jaspTools
        run: |
          install.packages('remotes')
          remotes::install_github('jasp-stats/jaspTools')
          jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Run unit tests
        run: source('tests/testthat.R')
        shell: Rscript {0}
